import Xarrow from "react-xarrows";

export default function Arrows({
  curveness = 0.3,
  strokeWidth = 1,
  path = "grid",
  gridBreak = "10%",
  zIndex = "-1",
}) {
  return (
    <>
      <Xarrow
        start={"0"}
        end={"8"}
        curveness={curveness}
        strokeWidth={strokeWidth}
        path={path}
        gridBreak={gridBreak}
        zIndex={zIndex}
      />
      <Xarrow
        start={"1"}
        end={"8"}
        curveness={curveness}
        strokeWidth={strokeWidth}
        path={path}
        gridBreak={gridBreak}
        zIndex={zIndex}
      />
      <Xarrow
        start={"2"}
        end={"9"}
        curveness={curveness}
        strokeWidth={strokeWidth}
        path={path}
        gridBreak={gridBreak}
        zIndex={zIndex}
      />
      <Xarrow
        start={"3"}
        end={"9"}
        curveness={curveness}
        strokeWidth={strokeWidth}
        path={path}
        gridBreak={gridBreak}
        zIndex={zIndex}
      />
      <Xarrow
        start={"4"}
        end={"10"}
        curveness={curveness}
        strokeWidth={strokeWidth}
        path={path}
        gridBreak={gridBreak}
        zIndex={zIndex}
      />
      <Xarrow
        start={"5"}
        end={"10"}
        curveness={curveness}
        strokeWidth={strokeWidth}
        path={path}
        gridBreak={gridBreak}
        zIndex={zIndex}
      />
      <Xarrow
        start={"6"}
        end={"11"}
        curveness={curveness}
        strokeWidth={strokeWidth}
        path={path}
        gridBreak={gridBreak}
        zIndex={zIndex}
      />
      <Xarrow
        start={"7"}
        end={"11"}
        curveness={curveness}
        strokeWidth={strokeWidth}
        path={path}
        gridBreak={gridBreak}
        zIndex={zIndex}
      />
      <Xarrow
        start={"8"}
        end={"12"}
        curveness={curveness}
        strokeWidth={strokeWidth}
        path={path}
        gridBreak={gridBreak}
        zIndex={zIndex}
      />
      <Xarrow
        start={"9"}
        end={"12"}
        curveness={curveness}
        strokeWidth={strokeWidth}
        path={path}
        gridBreak={gridBreak}
        zIndex={zIndex}
      />
      <Xarrow
        start={"10"}
        end={"13"}
        curveness={curveness}
        strokeWidth={strokeWidth}
        path={path}
        gridBreak={gridBreak}
        zIndex={zIndex}
      />
      <Xarrow
        start={"11"}
        end={"13"}
        curveness={curveness}
        strokeWidth={strokeWidth}
        path={path}
        gridBreak={gridBreak}
        zIndex={zIndex}
      />
      <Xarrow
        start={"12"}
        end={"14"}
        curveness={curveness}
        strokeWidth={strokeWidth}
        path={path}
        gridBreak={gridBreak}
        zIndex={zIndex}
      />
      <Xarrow
        start={"13"}
        end={"14"}
        curveness={curveness}
        strokeWidth={strokeWidth}
        path={path}
        gridBreak={gridBreak}
        zIndex={zIndex}
      />
    </>
  );
}
